# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(838, 469)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.CurrentBeamTab = QtWidgets.QWidget()
        self.CurrentBeamTab.setObjectName("CurrentBeamTab")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.CurrentBeamTab)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.CurrentBeamTab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelOutput = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.labelOutput.setFont(font)
        self.labelOutput.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.labelOutput.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelOutput.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOutput.setObjectName("labelOutput")
        self.verticalLayout.addWidget(self.labelOutput)
        self.labelFlatX = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.labelFlatX.setFont(font)
        self.labelFlatX.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.labelFlatX.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelFlatX.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFlatX.setObjectName("labelFlatX")
        self.verticalLayout.addWidget(self.labelFlatX)
        self.labelFlatY = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.labelFlatY.setFont(font)
        self.labelFlatY.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.labelFlatY.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelFlatY.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFlatY.setObjectName("labelFlatY")
        self.verticalLayout.addWidget(self.labelFlatY)
        self.labelSymX = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.labelSymX.setFont(font)
        self.labelSymX.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.labelSymX.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelSymX.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSymX.setObjectName("labelSymX")
        self.verticalLayout.addWidget(self.labelSymX)
        self.labelSymY = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.labelSymY.setFont(font)
        self.labelSymY.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.labelSymY.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelSymY.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSymY.setObjectName("labelSymY")
        self.verticalLayout.addWidget(self.labelSymY)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButtonStart = QtWidgets.QPushButton(self.CurrentBeamTab)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons/Start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonStart.setIcon(icon)
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.verticalLayout_6.addWidget(self.pushButtonStart)
        self.pushButtonStop = QtWidgets.QPushButton(self.CurrentBeamTab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons/stop 2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonStop.setIcon(icon1)
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.verticalLayout_6.addWidget(self.pushButtonStop)
        self.checkBoxBatchAnalyse = QtWidgets.QCheckBox(self.CurrentBeamTab)
        self.checkBoxBatchAnalyse.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icons/basket.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBoxBatchAnalyse.setIcon(icon2)
        self.checkBoxBatchAnalyse.setChecked(True)
        self.checkBoxBatchAnalyse.setObjectName("checkBoxBatchAnalyse")
        self.verticalLayout_6.addWidget(self.checkBoxBatchAnalyse)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.gridLayout_13.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.CurrentBeamTab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.groupBox_2)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout_4.addWidget(self.calendarWidget)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.gridLayout_10.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.CurrentBeamTab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setStyleSheet("background-image: url(:/newPrefix/icons/EPID.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 1, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_3, 0, 2, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        self.tabWidget.addTab(self.CurrentBeamTab, "")
        self.AllBeamsTab = QtWidgets.QWidget()
        self.AllBeamsTab.setObjectName("AllBeamsTab")
        self.gridLayout = QtWidgets.QGridLayout(self.AllBeamsTab)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.AllBeamsTab)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.AllBeamsTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.splitter = QtWidgets.QSplitter(self.tab)
        self.splitter.setGeometry(QtCore.QRect(0, 10, 329, 364))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.groupBoxSettings = QtWidgets.QGroupBox(self.splitter)
        self.groupBoxSettings.setEnabled(True)
        self.groupBoxSettings.setAutoFillBackground(True)
        self.groupBoxSettings.setCheckable(False)
        self.groupBoxSettings.setObjectName("groupBoxSettings")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBoxSettings)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox6X = QtWidgets.QGroupBox(self.groupBoxSettings)
        self.groupBox6X.setEnabled(True)
        self.groupBox6X.setObjectName("groupBox6X")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox6X)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox6X)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.doubleSpinBoxSlope6X = QtWidgets.QDoubleSpinBox(self.groupBox6X)
        self.doubleSpinBoxSlope6X.setEnabled(False)
        self.doubleSpinBoxSlope6X.setDecimals(4)
        self.doubleSpinBoxSlope6X.setMinimum(-20000.0)
        self.doubleSpinBoxSlope6X.setMaximum(20000.0)
        self.doubleSpinBoxSlope6X.setSingleStep(5.0)
        self.doubleSpinBoxSlope6X.setProperty("value", 10638.0)
        self.doubleSpinBoxSlope6X.setObjectName("doubleSpinBoxSlope6X")
        self.horizontalLayout.addWidget(self.doubleSpinBoxSlope6X)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox6X)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.doubleSpinBoxIntercept6X = QtWidgets.QDoubleSpinBox(self.groupBox6X)
        self.doubleSpinBoxIntercept6X.setEnabled(False)
        self.doubleSpinBoxIntercept6X.setDecimals(4)
        self.doubleSpinBoxIntercept6X.setMinimum(-10.0)
        self.doubleSpinBoxIntercept6X.setMaximum(10.0)
        self.doubleSpinBoxIntercept6X.setSingleStep(0.5)
        self.doubleSpinBoxIntercept6X.setProperty("value", -7.3919)
        self.doubleSpinBoxIntercept6X.setObjectName("doubleSpinBoxIntercept6X")
        self.horizontalLayout_2.addWidget(self.doubleSpinBoxIntercept6X)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout_9.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox6X)
        self.groupBox18X = QtWidgets.QGroupBox(self.groupBoxSettings)
        self.groupBox18X.setObjectName("groupBox18X")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox18X)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.groupBox18X)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.doubleSpinBoxSlope18X = QtWidgets.QDoubleSpinBox(self.groupBox18X)
        self.doubleSpinBoxSlope18X.setEnabled(False)
        self.doubleSpinBoxSlope18X.setDecimals(4)
        self.doubleSpinBoxSlope18X.setMinimum(-20000.0)
        self.doubleSpinBoxSlope18X.setMaximum(20000.0)
        self.doubleSpinBoxSlope18X.setSingleStep(5.0)
        self.doubleSpinBoxSlope18X.setProperty("value", 12090.0)
        self.doubleSpinBoxSlope18X.setObjectName("doubleSpinBoxSlope18X")
        self.horizontalLayout_8.addWidget(self.doubleSpinBoxSlope18X)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.groupBox18X)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.doubleSpinBoxIntercept18X = QtWidgets.QDoubleSpinBox(self.groupBox18X)
        self.doubleSpinBoxIntercept18X.setEnabled(False)
        self.doubleSpinBoxIntercept18X.setDecimals(4)
        self.doubleSpinBoxIntercept18X.setMinimum(-10.0)
        self.doubleSpinBoxIntercept18X.setMaximum(10.0)
        self.doubleSpinBoxIntercept18X.setSingleStep(0.5)
        self.doubleSpinBoxIntercept18X.setProperty("value", -1.3842)
        self.doubleSpinBoxIntercept18X.setObjectName("doubleSpinBoxIntercept18X")
        self.horizontalLayout_9.addWidget(self.doubleSpinBoxIntercept18X)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_9)
        self.gridLayout_7.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox18X)
        self.groupBox6X_3 = QtWidgets.QGroupBox(self.groupBoxSettings)
        self.groupBox6X_3.setEnabled(True)
        self.groupBox6X_3.setObjectName("groupBox6X_3")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox6X_3)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_14 = QtWidgets.QLabel(self.groupBox6X_3)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_17.addWidget(self.label_14)
        self.doubleSpinBoxSlope6XSRS = QtWidgets.QDoubleSpinBox(self.groupBox6X_3)
        self.doubleSpinBoxSlope6XSRS.setEnabled(False)
        self.doubleSpinBoxSlope6XSRS.setDecimals(4)
        self.doubleSpinBoxSlope6XSRS.setMinimum(-20000.0)
        self.doubleSpinBoxSlope6XSRS.setMaximum(20000.0)
        self.doubleSpinBoxSlope6XSRS.setSingleStep(5.0)
        self.doubleSpinBoxSlope6XSRS.setProperty("value", 10638.0)
        self.doubleSpinBoxSlope6XSRS.setObjectName("doubleSpinBoxSlope6XSRS")
        self.horizontalLayout_17.addWidget(self.doubleSpinBoxSlope6XSRS)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_15 = QtWidgets.QLabel(self.groupBox6X_3)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_18.addWidget(self.label_15)
        self.doubleSpinBoxIntercept6XSRS = QtWidgets.QDoubleSpinBox(self.groupBox6X_3)
        self.doubleSpinBoxIntercept6XSRS.setEnabled(False)
        self.doubleSpinBoxIntercept6XSRS.setDecimals(4)
        self.doubleSpinBoxIntercept6XSRS.setMinimum(-100.0)
        self.doubleSpinBoxIntercept6XSRS.setMaximum(100.0)
        self.doubleSpinBoxIntercept6XSRS.setSingleStep(0.5)
        self.doubleSpinBoxIntercept6XSRS.setProperty("value", -7.3919)
        self.doubleSpinBoxIntercept6XSRS.setObjectName("doubleSpinBoxIntercept6XSRS")
        self.horizontalLayout_18.addWidget(self.doubleSpinBoxIntercept6XSRS)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_18)
        self.gridLayout_18.addLayout(self.horizontalLayout_16, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox6X_3)
        self.gridLayout_8.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBoxSettings)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEditImageFolder = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditImageFolder.setEnabled(False)
        self.lineEditImageFolder.setObjectName("lineEditImageFolder")
        self.gridLayout_6.addWidget(self.lineEditImageFolder, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBoxSettings)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.comboBoxLA = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBoxLA.setEnabled(False)
        self.comboBoxLA.setObjectName("comboBoxLA")
        self.comboBoxLA.addItem("")
        self.comboBoxLA.addItem("")
        self.comboBoxLA.addItem("")
        self.comboBoxLA.addItem("")
        self.gridLayout_5.addWidget(self.comboBoxLA, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox_5)
        self.gridLayout_8.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButtonLogin = QtWidgets.QPushButton(self.groupBoxSettings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonLogin.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icons/arrow_up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonLogin.setIcon(icon3)
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.horizontalLayout_4.addWidget(self.pushButtonLogin)
        self.pushButtonLogout = QtWidgets.QPushButton(self.groupBoxSettings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonLogout.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/icons/arrow_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonLogout.setIcon(icon4)
        self.pushButtonLogout.setObjectName("pushButtonLogout")
        self.horizontalLayout_4.addWidget(self.pushButtonLogout)
        self.gridLayout_8.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(350, 20, 261, 141))
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelDBPath = QtWidgets.QGroupBox(self.groupBox_6)
        self.labelDBPath.setObjectName("labelDBPath")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.labelDBPath)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.pushButtonToXLS = QtWidgets.QPushButton(self.labelDBPath)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/icons/application_view_columns.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonToXLS.setIcon(icon5)
        self.pushButtonToXLS.setObjectName("pushButtonToXLS")
        self.gridLayout_11.addWidget(self.pushButtonToXLS, 1, 0, 1, 1)
        self.lineEditDBFile = QtWidgets.QLineEdit(self.labelDBPath)
        self.lineEditDBFile.setObjectName("lineEditDBFile")
        self.gridLayout_11.addWidget(self.lineEditDBFile, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.labelDBPath)
        self.gridLayout_12.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.splitter_2 = QtWidgets.QSplitter(self.tab_4)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.pushButtonLoadImages = QtWidgets.QPushButton(self.layoutWidget_2)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/icons/open alt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonLoadImages.setIcon(icon6)
        self.pushButtonLoadImages.setObjectName("pushButtonLoadImages")
        self.horizontalLayout_10.addWidget(self.pushButtonLoadImages)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.layoutWidget_2)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget_2.verticalHeader().setMinimumSectionSize(15)
        self.verticalLayout_8.addWidget(self.tableWidget_2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget_2)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/icons/advanced.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon7)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_11.addWidget(self.pushButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.groupBox_7 = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.CalibrationPlot = MatplotlibWidget(self.groupBox_7)
        self.CalibrationPlot.setStyleSheet("background-color: rgb(179, 179, 179);")
        self.CalibrationPlot.setObjectName("CalibrationPlot")
        self.gridLayout_15.addWidget(self.CalibrationPlot, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 259, 297))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_8.setObjectName("label_8")
        self.frame = QtWidgets.QFrame(self.tab_2)
        self.frame.setGeometry(QtCore.QRect(10, 260, 261, 111))
        self.frame.setStyleSheet("image: url(:/newPrefix/icons/ACT.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(630, 340, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setFrameShape(QtWidgets.QFrame.Box)
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.labelBlinkText = QtWidgets.QLabel(self.centralwidget)
        self.labelBlinkText.setObjectName("labelBlinkText")
        self.horizontalLayout_12.addWidget(self.labelBlinkText)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_12.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 838, 21))
        self.menubar.setObjectName("menubar")
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")


        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Energy"))
        self.labelOutput.setText(_translate("MainWindow", "Output"))
        self.labelFlatX.setText(_translate("MainWindow", "FlatX"))
        self.labelFlatY.setText(_translate("MainWindow", "FlatY"))
        self.labelSymX.setText(_translate("MainWindow", "SymX"))
        self.labelSymY.setText(_translate("MainWindow", "SymY"))
        self.pushButtonStart.setText(_translate("MainWindow", "Start"))
        self.pushButtonStop.setText(_translate("MainWindow", "Stop"))
        self.checkBoxBatchAnalyse.setText(_translate("MainWindow", "Batch Analyse"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Calander"))
        self.label_3.setText(_translate("MainWindow", "Action level(<2%)"))
        self.label_4.setText(_translate("MainWindow", ">Action level(<3%)"))
        self.label_5.setText(_translate("MainWindow", ">Tolerance level(>3%)"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Setup"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p>Field Size:20 x 20(6X &amp; 18X), 15 x 15 (6XSRS)</p><p>Detector Position: 0,0,0 (Lat, Long, vrt)</p><p>MU: 200</p><p>Dose Rate: 600 MU/min (6X &amp; 18X), 100 MU/min (6XSRS)</p><p>EPID Mode:Integrated</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CurrentBeamTab), _translate("MainWindow", "CurrentBeam"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Energy"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Output (%)"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "FlatX (%)"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "FlatY (%)"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "SymX (%)"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "SymY (%)"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "MPV"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Time"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AllBeamsTab), _translate("MainWindow", "AllBeams"))
        self.groupBoxSettings.setTitle(_translate("MainWindow", "Output Calibration"))
        self.groupBox6X.setTitle(_translate("MainWindow", "6X"))
        self.label.setText(_translate("MainWindow", "Slope"))
        self.label_2.setText(_translate("MainWindow", "Intercept"))
        self.groupBox18X.setTitle(_translate("MainWindow", "18X"))
        self.label_6.setText(_translate("MainWindow", "Slope"))
        self.label_7.setText(_translate("MainWindow", "Intercept"))
        self.groupBox6X_3.setTitle(_translate("MainWindow", "6XSRS"))
        self.label_14.setText(_translate("MainWindow", "Slope"))
        self.label_15.setText(_translate("MainWindow", "Intercept"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Image Folder Path"))
        self.lineEditImageFolder.setToolTip(_translate("MainWindow", "<html><head/><body><p>Path without \'LinacID\\\' at end</p></body></html>"))
        self.lineEditImageFolder.setText(_translate("MainWindow", "D:\\DailyCheck\\Data"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Linac"))
        self.comboBoxLA.setItemText(0, _translate("MainWindow", "LA1"))
        self.comboBoxLA.setItemText(1, _translate("MainWindow", "LA2"))
        self.comboBoxLA.setItemText(2, _translate("MainWindow", "LA3"))
        self.comboBoxLA.setItemText(3, _translate("MainWindow", "LA4"))
        self.pushButtonLogin.setText(_translate("MainWindow", "Login"))
        self.pushButtonLogout.setText(_translate("MainWindow", "Logout"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Database"))
        self.labelDBPath.setTitle(_translate("MainWindow", "DB File"))
        self.pushButtonToXLS.setText(_translate("MainWindow", "To XLS"))
        self.lineEditDBFile.setText(_translate("MainWindow", "D:\\DailyCheck\\DailyQA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Settings"))
        self.pushButtonLoadImages.setToolTip(_translate("MainWindow", "Energy automatically detected"))
        self.pushButtonLoadImages.setText(_translate("MainWindow", "Load Images (seperate set for each energy)"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No."))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "MU"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "MPV"))
        self.pushButton.setToolTip(_translate("MainWindow", "Energy automatically detected"))
        self.pushButton.setText(_translate("MainWindow", "Calibrate"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Fitting"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Calibration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Trend"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Developed by:</span></p><p>Jothy Selvaraj</p><p>Jon Lee</p><p>Ben Cooper</p><p><span style=\" font-weight:600;\">Medical Physics &amp; Radiation Engineering</span></p><p><span style=\" font-weight:600;\">The Canberra Hospital</span></p><p><span style=\" font-weight:600;\">Garran, 2605, ACT</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "Last Build:20/12/2016 -JKS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "About"))
        self.labelBlinkText.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#ff0000;\">Click &quot;Start&quot; after transfering images to NAS to analyse</span></p></body></html>"))

from matplotlibwidget import MatplotlibWidget
import Resource_file_rc
